services:
  - type: web
    name: mediscan-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend main:app
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: JWT_SECRET_KEY
        generateValue: true
